app:
  name: 'go-clean-template'
  version: '2.1.2'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2
  pg_url: 'postgres://username:password@localhost:5432/dbname'

rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'
  rmq_url: 'amqp://guest:guest@localhost:5672/'
